* libgen_dl
** Usage: libgen_dl "search term"
** Navigating through results:
*** up/(p)
    go up through results
*** down/(n)
    go down through results
*** space/(m)
    mark a result for download (currently multiple simulatenous
    downloads are buggy)
*** (d)
    download currently selected results. if no results are selected,
    will download the result currently highlighted. currently the
    files will be saved to $cwd/[Author][Year].[file extension].
*** s
    quarter-implemented interactive search-term updating, won't show
    you what you're typing (yet.)
** Notes
*** Mirrors
    We only support library.lol and the Cloudflare IPFS gateway for
    downloads. This combination seems to have just about universal
    coverage, is very fast and has good uptime. Adding more mirrors
    would complicate the implementation and maintenance quite a
    bit. Patches and feature requests for adding mirrors would only be
    accepted if you can demonstrate that the currently implemented
    mirror doesn't have adequate coverage of the libgen catalogue.
*** UTF-8 bug
    There is a known bug where some queries crash the downloader due
    to malformed UTF-8 in the title text. I don't know how to use any
    OCaml UTF-8 libraries, and the ones I've looked at appear
    undocumented. Stay tuned for a fix.
*** More planned features, bug fixes
    See ~design.org~ for planned features and bugfixes.
** FAQ
*** Isn't webscraping stupid and error prone?
    Yes. Libgen doesn't have a proper API for searching, however, so
    some amount of webscraping is necessary to get the book IDs
    required to query their json API. Furthermore, once you have
    scraped the book IDs and have the option to query the json API for
    structured data about the books related to your query, each API
    call is really slow. The delays worked against another
    unmaintained [[https://github.com/ciehanski/libgen-cli][libgen downloader]] I fixed recently (before running
    into Go module hell.)

    I aim to make the webscaping aspects of this tool as modular as
    possible. Even if I stop maintaing it someone could easily come
    along and fix the scraping without modifying anything else about
    the tool.

    One more speculation about this: libgen's json API is, as far as I
    gather, primarily intended for internal use. It wouldn't surprise
    me, therefore, if it were more subject to flux than the
    public-facing HTML that has remained as far as I can tell mostly
    stable for the past few years
